---
- hosts: localhost
  tasks:
    - name: Launch a new container
      docker_container:
        name: my-container
        image: greatbsky/sshcentos7
        state: started
        detach: yes
        interactive: yes
        tty: yes
        ports:
          - "80:80"

    - name: Container details
      docker_container_info:
        name: "my-container"
      register: containerinfo

    - debug:
        var: containerinfo.container.NetworkSettings.IPAddress

    - name: Create inventory file
      template:
        src: ./inventory_template
        dest: /tmp/inventory/inventory_template

- hosts: docker
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: enabled

    - name: Copy webpage
      copy:
        src: index.html
        dest: /var/www/html/index.html
